development:
  clients:
    default:
      uri: <%= ENV['PACK_DATABASE_URI'] %>
test:
  clients:
    default:
      uri: <%= ENV['PACK_DATABASE_URI'] %>
production:
  clients:
    default:
      uri: <%= ENV['PACK_DATABASE_URI'] %>
