development:
  clients:
    default:
      database: <%= ENV['PACK_DATABASE'] %>
      hosts:
        - <%= "#{ENV['PACK_DATABASE_HOST']}:#{ENV['PACK_DATABASE_PORT']}" %>
test:
  clients:
    default:
      database: <%= ENV['PACK_DATABASE'] %>
      hosts:
        - <%= "#{ENV['PACK_DATABASE_HOST']}:#{ENV['PACK_DATABASE_PORT']}" %>
production:
  clients:
    default:
      uri: <%= ENV['PACK_DATABASE_URI'] %>
